import style from './Main.module.scss'
export const Main = () => {
    return(
        <main className={style.wrapper}>
        <article className={style.article1}> <p>I'm baby godard schlitz typewriter quinoa bushwick chillwave biodiesel air plant whatever, microdosing XOXO actually glossier kale chips. Trust fund tofu poke live-edge la croix plaid. Woke brunch occupy offal kickstarter 90's. Copper mug fixie 3 wolf moon, adaptogen flannel meggings etsy. Lyft bushwick pug, gochujang portland chicharrones waistcoat affogato fanny pack shoreditch tbh squid. Vice 8-bit cray, 90's aesthetic man braid put a bird on it migas deep v jianbing tousled stumptown listicle. Godard hot chicken blog, chartreuse trust fund unicorn keffiyeh.</p></article> 
        <article className={style.article2}> <p>Typewriter vinyl kinfolk salvia crucifix kitsch chillwave gluten-free letterpress artisan seitan williamsburg. Chicharrones franzen af viral sartorial jean shorts locavore squid enamel pin. Woke pok pok before they sold out cardigan jianbing meggings pug yuccie post-ironic distillery tofu drinking vinegar fashion axe blue bottle. Kitsch quinoa raw denim adaptogen master cleanse raclette. Tote bag cred enamel pin seitan vape 3 wolf moon taiyaki XOXO microdosing. Adaptogen bushwick tote bag selfies, swag taiyaki vinyl af echo park.</p></article> 
        <article className={style.article3}> <p>Selvage microdosing glossier vape flannel next level mustache cray kinfolk portland. Street art lomo scenester, adaptogen stumptown jean shorts bicycle rights deep v viral subway tile master cleanse portland. Cred cronut truffaut poke viral mumblecore, kogi waistcoat meh. Letterpress selfies mustache palo santo, deep v banjo vinyl wayfarers pickled beard snackwave. Edison bulb bushwick asymmetrical mlkshk kitsch godard, master cleanse meggings.</p></article> 
        <article className={style.article4}> <p>Before they sold out cardigan mustache church-key la croix keffiyeh. Pork belly flannel organic fingerstache ugh neutra. Food truck tattooed austin unicorn poutine four loko keffiyeh. Adaptogen four dollar toast cold-pressed microdosing. 3 wolf moon small batch pickled austin. Hexagon gluten-free echo park put a bird on it knausgaard wayfarers everyday carry pickled blog. Hot chicken cardigan polaroid lo-fi, health goth sartorial fam yr pitchfork succulents vaporware semiotics tofu fingerstache farm-to-table.</p></article> 
        <article className={style.article5}> <p>Ethical blue bottle gluten-free enamel pin, hell of shaman gentrify everyday carry. Shaman pabst keffiyeh sriracha viral pork belly copper mug bitters art party adaptogen paleo next level umami crucifix. Gochujang humblebrag helvetica viral. Distillery taxidermy aesthetic hell of affogato, kogi woke brunch beard etsy. Chambray la croix pitchfork synth banh mi adaptogen. Ennui authentic skateboard, ramps fanny pack coloring book photo booth flannel chicharrones sartorial small batch single-origin coffee.</p></article> 

        </main>
    )
}